Firewall edits
civo/cli-rubygem pull request #10
Opened 2019-06-18 11:31 UTC by kaihoffman

Implements Firewall/Firewallrule methods:

- Create Firewall
- List Firewalls
- Remove Firewall

- New Rule
- List Rules
- Delete Rule

2019-06-18 12:43 UTC, andyjeffries requested changes

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +      puts "        Created firewall #{firewall_name.colorize(:green)}"
Same problem as before - crazy indentation before the output...

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +      puts "        Removed firewall #{firewall_ID.colorize(:red)}"
Again

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +    desc "new_rule", "Create new rule on firewall firewall_name called rule_name with required arguments"
Not a fan of using _ in command names, `civo firewall new-rule` looks better.

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +      puts "        New rule" + (options[:label].nil? ? "" : " #{options[:label].colorize(:green)}") + " created"
Again crazy spacing.

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +    desc "new_rule", "Create new rule on firewall firewall_name called rule_name with required arguments"
Not sure how that works with method names though, you may need to research that...

2019-06-18 12:43 UTC, andyjeffries commented on lib/firewall.rb
> +      puts "        Removed Firewall rule #{rule_id.colorize(:red)}"
Spacing...

2019-06-18 13:10 UTC, kaihoffman commented on lib/firewall.rb
> +      puts "        Created firewall #{firewall_name.colorize(:green)}"
Sorry to miss this from the fixes. Changing all.

2019-06-18 13:12 UTC, andyjeffries commented on lib/firewall.rb
> +      puts "        Created firewall #{firewall_name.colorize(:green)}"
👍

2019-06-18 13:14 UTC, kaihoffman commented on lib/firewall.rb
> +    desc "new_rule", "Create new rule on firewall firewall_name called rule_name with required arguments"
Ruby doesn't allow hyphens in method names. Option would be to have it be called `newrule` for: `civo firewall newrule --firewall_id=98babh3...`

2019-06-19 08:41 UTC, andyjeffries commented on lib/firewall.rb
> +    desc "new_rule", "Create new rule on firewall firewall_name called rule_name with required arguments"
LOL! I know that. I meant maybe thor will allow you to use a hyphenated command internally call the underscore version ;-)

2019-06-19 08:42 UTC, andyjeffries commented on lib/firewall.rb
> +    desc "new_rule", "Create new rule on firewall firewall_name called rule_name with required arguments"
https://stackoverflow.com/questions/40064574/hyphenated-subcommand-in-thor

2019-06-19 09:01 UTC, merged