Instance creation
civo/cli-rubygem pull request #11
Opened 2019-06-20 13:33 UTC by kaihoffman

Adds a random name generator feature if a user doesn't provide a HOSTNAME for instance#create

Unifies all the help text in instance methods to use ID/HOSTNAME.

Implements long_desc in instance#create to clean up the help text.

2019-06-20 14:22 UTC, andyjeffries requested changes

2019-06-20 14:22 UTC, andyjeffries commented on lib/instance.rb
> +    desc "create [HOSTNAME] [--options]", "create a new instance with specified hostname, instance size, template/snapshot ID. Optional: region, public_ip (true or false), initial user"
Not a fan of `[--options]` in there because it feels like that is the flag. Maybe use `[...]` to show there are more options instead.

2019-06-20 14:22 UTC, andyjeffries commented on lib/instance.rb
> +      \x5 --tags=<'tag1 tag2 tag3...'>
What are all the `\x5` for?

The help also says "instance size (default: g2.small)" without specifying what the actual command line option for it is (same for template/snapshot ID - and don't say "image template", that's weird in our terminology).

The `--public_ip` option should be clearer when using `from` and is that how you specify it (you normally need an instance ID to take it from)

`civo_ssh_uuid` should be `ssh_key_id` (no need to specify `civo` and we always call them the `id` of the object, the fact that it happens to be a UUID is not important)

2019-06-20 14:22 UTC, andyjeffries commented on lib/instance.rb
> +    desc "update ID/HOSTNAME [--name] [--notes]", "update details of instance. Use --hostname=new_name, --notes='notes' to specify update"
This feels like it should be split again - the short desc is just `update details of instance`, then the stuff about flags goes in a longer description.

2019-06-20 14:25 UTC, kaihoffman commented on lib/instance.rb
> +    desc "create [HOSTNAME] [--options]", "create a new instance with specified hostname, instance size, template/snapshot ID. Optional: region, public_ip (true or false), initial user"
So just have it be `create [HOSTNAME] [...]` or `create [HOSTNAME] [options...]`? Just want to get it right!

2019-06-20 14:31 UTC, kaihoffman commented on lib/instance.rb
> +      \x5 --tags=<'tag1 tag2 tag3...'>
`\x5` is a line break as per Thor guide here: http://whatisthor.com/ It is done for layout of the long_desc printout. I initially used `\n` but noticed the syntax on that site using the escape sequence instead.

Fixing the other bits now.

2019-06-20 14:31 UTC, kaihoffman commented on lib/instance.rb
> +    desc "update ID/HOSTNAME [--name] [--notes]", "update details of instance. Use --hostname=new_name, --notes='notes' to specify update"
You got it.

2019-06-20 14:31 UTC, andyjeffries commented on lib/instance.rb
> +    desc "create [HOSTNAME] [--options]", "create a new instance with specified hostname, instance size, template/snapshot ID. Optional: region, public_ip (true or false), initial user"
The former :-)

2019-06-20 14:32 UTC, andyjeffries commented on lib/instance.rb
> +      \x5 --tags=<'tag1 tag2 tag3...'>
Interesting, never knew that one. Thanks.

2019-06-20 14:42 UTC, kaihoffman commented on lib/instance.rb
> +      \x5 --tags=<'tag1 tag2 tag3...'>
Yeah, not something I'd encountered knowingly before!

2019-06-21 08:11 UTC, andyjeffries requested changes
Other than that one point, all good now.

2019-06-21 08:11 UTC, andyjeffries commented on lib/instance.rb
> +    desc "update ID/HOSTNAME [--name] [--notes]", "update details of instance."
Line 83 of this file doesn't end the help text in `desc` with a `.`, but this one does. They should all be consistent (and I would say without).

2019-06-21 08:15 UTC, kaihoffman commented on lib/instance.rb
> +    desc "update ID/HOSTNAME [--name] [--notes]", "update details of instance."
Hah, that's my oversight (writing something resembling full sentences and automatically putting a full stop at the end).

2019-06-21 08:18 UTC, merged